const houses = [
  {
    id: 'harbour-view-residence',
    name: 'Harbour View Residence',
    type: 'Contemporary Villa',
    location: 'Takapuna, Auckland',
    price: 1280000,
    status: 'For sale',
    bedrooms: 4,
    bathrooms: 3,
    area: '286 m²',
    lotSize: '612 m²',
    yearBuilt: 2021,
    parking: 'Double garage',
    summary:
      'A light-filled coastal villa with harbour outlooks, considered finishes, and generous spaces for entertaining.',
    description:
      'Harbour View Residence is a carefully composed coastal home designed around light, privacy, and effortless connection to the water. The main living level opens through wide glass sliders to a landscaped courtyard and elevated terrace, creating a natural flow between the kitchen, dining room, and outdoor entertaining area. Inside, warm oak flooring balances crisp architectural lines, while the stone kitchen, tailored joinery, and quiet study provide the polish expected of a contemporary villa. The upper-level suite captures the best of the harbour outlook and gives the home a peaceful retreat from its social spaces.',
    highlights:
      'Morning harbour views, a north-facing terrace, and a flexible media room make this a polished home for both everyday life and relaxed entertaining.',
    amenities: [
      'Designer kitchen with integrated appliances',
      'Ducted heat pump system',
      'Underfloor heating in bathrooms',
      'Secure video entry',
      'Rainwater collection for garden irrigation',
    ],
    neighborhood:
      'Set close to Takapuna Beach, local cafes, schools, and the North Shore transport network, the residence offers an easy coastal lifestyle without giving up city access.',
    tenure: 'Freehold title',
    rates: 'Approx. NZ$5,840 per year',
    agent: 'Polaris Private Property Team',
    features: [
      'Open-plan kitchen with stone island',
      'Floor-to-ceiling double glazing',
      'Private landscaped courtyard',
      'Home office and media room',
      'Solar-ready roof and smart lighting',
    ],
    images: [
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1600&q=85',
    ],
  },
  {
    id: 'cedar-grove-house',
    name: 'Cedar Grove House',
    type: 'Family Home',
    location: 'Remuera, Auckland',
    price: 985000,
    status: 'For sale',
    bedrooms: 3,
    bathrooms: 2,
    area: '198 m²',
    lotSize: '438 m²',
    yearBuilt: 2018,
    parking: 'Covered carport',
    summary:
      'A warm, established family home with mature gardens, a sunny deck, and an easy indoor-outdoor layout.',
    description:
      'Cedar Grove House brings together the reassuring proportions of a family home and the relaxed feel of a garden retreat. The central living room is anchored by a feature timber wall and opens directly onto a west-facing deck for late afternoon gatherings. Three generous bedrooms include a private main suite, while a separate laundry, flexible study nook, and generous storage make the home practical as well as welcoming. Established planting frames the property from the street and creates a private green outlook from nearly every room.',
    highlights:
      'A beautifully maintained garden, broad entertaining deck, and practical single-level layout make this an inviting long-term family address.',
    amenities: [
      'Engineered oak flooring',
      'Gas fireplace and heat pump',
      'Double-glazed timber windows',
      'Raised vegetable beds',
      'Fibre internet connection',
    ],
    neighborhood:
      'Remuera village, sought-after schools, parks, and daily conveniences are all within easy reach, with the city centre a short drive away.',
    tenure: 'Freehold title',
    rates: 'Approx. NZ$4,920 per year',
    agent: 'Polaris Private Property Team',
    features: [
      'West-facing entertaining deck',
      'Engineered oak flooring',
      'Separate laundry room',
      'Mature native garden',
      'Walkable to local schools and cafes',
    ],
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600585152915-d208bec867a1?auto=format&fit=crop&w=1600&q=85',
    ],
  },
  {
    id: 'olive-ridge-retreat',
    name: 'Olive Ridge Retreat',
    type: 'Country Estate',
    location: 'Matakana, Auckland',
    price: 1765000,
    status: 'New listing',
    bedrooms: 5,
    bathrooms: 3,
    area: '342 m²',
    lotSize: '2.4 ha',
    yearBuilt: 2020,
    parking: 'Triple garage',
    summary:
      'A private country estate with a pool terrace, guest suite, orchard, and expansive rural views.',
    description:
      'Olive Ridge Retreat is a rare country holding that combines architectural clarity with the generosity of a rural setting. The five-bedroom main residence is arranged around a sunlit central living zone, with high ceilings, natural stone, and full-height glazing framing the changing landscape. A separate guest suite provides privacy for extended family or visitors, while the pool terrace, outdoor kitchen, orchard, and established olive grove turn the grounds into a destination of their own. Despite its sense of escape, the property remains close to Matakana markets, vineyards, beaches, and village amenities.',
    highlights:
      'A private pool, established olive grove, and versatile guest accommodation give this estate both lifestyle appeal and long-term flexibility.',
    amenities: [
      'Heated mineral swimming pool',
      'Outdoor kitchen and firepit',
      'Rainwater storage tanks',
      'Three-phase power to workshop',
      'Underfloor heating throughout living areas',
    ],
    neighborhood:
      'Matakana is known for its weekend markets, artisan producers, beaches, and relaxed village atmosphere, with Auckland accessible for city connections.',
    tenure: 'Freehold title',
    rates: 'Approx. NZ$6,780 per year',
    agent: 'Polaris Private Property Team',
    features: [
      'Heated mineral swimming pool',
      'Wraparound rural views',
      'Guest suite with private entry',
      'Orchard and established olive grove',
      'Workshop and triple garaging',
    ],
    images: [
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1600&q=85',
    ],
  },
  {
    id: 'the-glasshouse-on-kelburn',
    name: 'The Glasshouse on Kelburn',
    type: 'Architectural Townhouse',
    location: 'Kelburn, Wellington',
    price: 1125000,
    status: 'For sale',
    bedrooms: 3,
    bathrooms: 2,
    area: '176 m²',
    lotSize: '214 m²',
    yearBuilt: 2022,
    parking: 'Internal single garage',
    summary:
      'A refined, light-filled townhouse where glass, timber, and garden outlooks create a calm urban retreat.',
    description:
      'The Glasshouse on Kelburn is an intelligent contemporary home shaped by its elevated position and leafy outlook. A double-height stairwell brings daylight deep into the plan, while the open kitchen and living area connects to a private courtyard for easy entertaining. The upper-level main suite enjoys treetop views and a well-appointed ensuite, with two further bedrooms offering space for guests, children, or a home office. Carefully selected materials and excellent acoustic separation give this townhouse a quiet, finished character.',
    highlights:
      'Architect-designed interiors, a private garden courtyard, and a walkable position near the Botanic Garden and village amenities.',
    amenities: [
      'Induction kitchen with scullery',
      'Double-height glazed stairwell',
      'Acoustic double glazing',
      'EV-ready garage wiring',
      'Secure keyless entry',
    ],
    neighborhood:
      'A peaceful Kelburn address close to the Botanic Garden, university, village shops, and central Wellington transport links.',
    tenure: 'Freehold title',
    rates: 'Approx. NZ$4,680 per year',
    agent: 'Polaris Private Property Team',
    features: [
      'Architect-designed interiors',
      'Private landscaped courtyard',
      'Treetop outlook from main suite',
      'Internal access garage',
      'Separate study nook',
    ],
    images: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=85',
    ],
  },
  {
    id: 'pohutukawa-coast-house',
    name: 'Pohutukawa Coast House',
    type: 'Beachside Bungalow',
    location: 'Mount Maunganui, Bay of Plenty',
    price: 1495000,
    status: 'New listing',
    bedrooms: 4,
    bathrooms: 2,
    area: '224 m²',
    lotSize: '506 m²',
    yearBuilt: 2019,
    parking: 'Double garage',
    summary:
      'A relaxed beachside home with generous decks, coastal planting, and room for weekends that stretch into summer.',
    description:
      'Pohutukawa Coast House captures the easy rhythm of life by the sea. The open-plan living area is oriented to the north and opens onto wide timber decks, allowing the home to move naturally between indoor comfort and outdoor entertaining. Four bedrooms provide a flexible arrangement for family and guests, with the ground-floor suite ideal for visitors or independent teenagers. Durable finishes, abundant storage, and an outdoor shower make the property as practical as it is inviting after a morning at the beach.',
    highlights:
      'A short walk to the sand, generous entertaining decks, and a private outdoor shower make this a true coastal lifestyle home.',
    amenities: [
      'Outdoor shower and surf storage',
      'North-facing covered deck',
      'Heat pump in living area',
      'Built-in outdoor barbecue',
      'Low-maintenance coastal garden',
    ],
    neighborhood:
      'Enjoy the cafes, surf culture, walking trails, and broad beaches of Mount Maunganui with local schools and shops close by.',
    tenure: 'Freehold title',
    rates: 'Approx. NZ$5,360 per year',
    agent: 'Polaris Private Property Team',
    features: [
      'Four flexible bedrooms',
      'Covered outdoor entertaining',
      'Beach gear storage',
      'Private garden',
      'Walkable beach location',
    ],
    images: [
      'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=85',
    ],
  },
  {
    id: 'fern-bank-residence',
    name: 'Fern Bank Residence',
    type: 'Modern Family Home',
    location: "Havelock North, Hawke's Bay",
    price: 1240000,
    status: 'For sale',
    bedrooms: 4,
    bathrooms: 2,
    area: '248 m²',
    lotSize: '1,120 m²',
    yearBuilt: 2017,
    parking: 'Double garage plus studio bay',
    summary:
      'A generous garden property with a smart floor plan, sheltered entertaining, and room to grow.',
    description:
      'Fern Bank Residence offers the space and composure of a country town home with a level of finish that makes everyday living feel special. The living wing is arranged to catch afternoon sun and opens to a sheltered terrace overlooking lawns and mature planting. A separate studio bay provides an excellent creative workspace or home gym, while the four-bedroom plan gives growing households room to adapt. The property has been cared for with an emphasis on durability, warmth, and easy connection to the garden.',
    highlights:
      'A large, private section with a flexible studio bay and a sun-soaked terrace for family gatherings.',
    amenities: [
      'Wood-burning fireplace',
      'Covered alfresco terrace',
      'Garden irrigation system',
      'Separate studio or gym',
      'Fruit trees and raised beds',
    ],
    neighborhood:
      "Havelock North offers village cafes, excellent local produce, wineries, parks, and a strong community setting within Hawke's Bay.",
    tenure: 'Freehold title',
    rates: 'Approx. NZ$4,460 per year',
    agent: 'Polaris Private Property Team',
    features: [
      'Large landscaped section',
      'Separate studio bay',
      'Sheltered outdoor room',
      'Four double bedrooms',
      'Excellent storage',
    ],
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600585152915-d208bec867a1?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1600&q=85',
    ],
  },
  {
    id: 'summit-lane-penthouse',
    name: 'Summit Lane Penthouse',
    type: 'City Penthouse',
    location: 'Auckland Central, Auckland',
    price: 2190000,
    status: 'For sale',
    bedrooms: 3,
    bathrooms: 3,
    area: '231 m²',
    lotSize: 'Private rooftop terrace',
    yearBuilt: 2023,
    parking: 'Secure tandem parking',
    summary:
      'A private city residence with dramatic views, generous entertaining rooms, and a rooftop terrace above it all.',
    description:
      'Summit Lane Penthouse occupies the top level of a discreet boutique building and delivers a rare combination of privacy, scale, and central convenience. The main living space frames layered harbour and skyline views through full-height glazing, while a sculptural kitchen and dining area provide an elegant setting for entertaining. The private rooftop terrace is equipped for long summer evenings, and three ensuite-capable bedrooms allow the home to operate equally well as a primary residence, city base, or executive retreat.',
    highlights:
      'Panoramic city and harbour outlooks, a private rooftop terrace, and boutique-building privacy in the heart of Auckland.',
    amenities: [
      'Private lift access',
      'Smart climate and lighting controls',
      'Rooftop outdoor kitchen',
      'Secure parcel room',
      'Two side-by-side storage lockers',
    ],
    neighborhood:
      'Restaurants, galleries, the waterfront, and major business precincts are all within an easy walk, making this a highly connected city address.',
    tenure: 'Unit title with body corporate',
    rates: 'Approx. NZ$7,250 per year',
    agent: 'Polaris Private Property Team',
    features: [
      'Private lift lobby',
      'Panoramic harbour views',
      'Three generous suites',
      'Rooftop entertaining terrace',
      'Two secure car parks',
    ],
    images: [
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1600&q=85',
    ],
  },
  {
    id: 'the-terrace-at-lake-hayes',
    name: 'The Terrace at Lake Hayes',
    type: 'Alpine Retreat',
    location: 'Arrowtown, Queenstown',
    price: 2450000,
    status: 'Private release',
    bedrooms: 4,
    bathrooms: 3,
    area: '310 m²',
    lotSize: '1,860 m²',
    yearBuilt: 2020,
    parking: 'Double garage with gear room',
    summary:
      'A warm architectural retreat framed by mountain light, lake air, and generous spaces for gathering.',
    description:
      'The Terrace at Lake Hayes is an alpine home with a strong sense of arrival and a deeply comfortable interior life. Natural stone, oak, and wool textures soften the clean architectural envelope, while expansive windows draw the surrounding peaks into the living spaces. The plan includes a generous bunk or guest room, a dedicated gear room, and a sheltered terrace positioned for afternoon sun. It is a retreat designed for both quiet weekends and memorable gatherings in every season.',
    highlights:
      'Mountain views, a sheltered terrace, and thoughtful ski and outdoor gear facilities create a true four-season retreat.',
    amenities: [
      'Hydronic underfloor heating',
      'Stone hearth fireplace',
      'Heated gear room',
      'Outdoor cedar hot tub',
      'Integrated sound system',
    ],
    neighborhood:
      'A short drive from Arrowtown village, Lake Hayes, and Queenstown recreation, with direct access to trails, vineyards, and ski fields.',
    tenure: 'Freehold title',
    rates: 'Approx. NZ$8,120 per year',
    agent: 'Polaris Private Property Team',
    features: [
      'Mountain and lake outlooks',
      'Outdoor cedar hot tub',
      'Dedicated gear room',
      'Four-season entertaining terrace',
      'Guest accommodation',
    ],
    images: [
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1600&q=85',
    ],
  },
  {
    id: 'mariner-house',
    name: 'Mariner House',
    type: 'Waterfront Residence',
    location: 'Devonport, Auckland',
    price: 1980000,
    status: 'For sale',
    bedrooms: 4,
    bathrooms: 3,
    area: '267 m²',
    lotSize: '584 m²',
    yearBuilt: 2016,
    parking: 'Double garage',
    summary:
      'A gracious waterfront home with a private jetty outlook, generous living rooms, and an elegant garden setting.',
    description:
      'Mariner House is a generous waterfront residence with a quiet, collected character. The home has been planned for the way people actually live, with a formal sitting room for winter evenings, an open kitchen and family room for daily life, and a broad terrace that looks towards the water. The upper-level main suite includes a private balcony, while the lower guest room and full bathroom provide flexibility for visitors or multigenerational living. Mature gardens soften the boundaries and create a rare sense of privacy by the shore.',
    highlights:
      'Water views from multiple rooms, mature gardens, and a flexible layout suited to both family life and hosting.',
    amenities: [
      'Water-facing entertaining terrace',
      'Private mooring access nearby',
      'Gas fireplace',
      'Security alarm system',
      'Landscaped garden with irrigation',
    ],
    neighborhood:
      'Devonport village, ferry connections, beaches, and local dining are close by, with the Auckland CBD accessible across the harbour.',
    tenure: 'Freehold title',
    rates: 'Approx. NZ$6,940 per year',
    agent: 'Polaris Private Property Team',
    features: [
      'Water views from main rooms',
      'Private upper balcony',
      'Flexible guest accommodation',
      'Mature landscaped garden',
      'Close to ferry and village',
    ],
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=85',
    ],
  },
  {
    id: 'manuka-hill-farmlet',
    name: 'Manuka Hill Farmlet',
    type: 'Lifestyle Property',
    location: 'Cambridge, Waikato',
    price: 1590000,
    status: 'For sale',
    bedrooms: 4,
    bathrooms: 2,
    area: '238 m²',
    lotSize: '4.8 ha',
    yearBuilt: 2015,
    parking: 'Double garage plus barn',
    summary:
      'A beautifully appointed lifestyle property with productive land, open skies, and a home built for unhurried days.',
    description:
      'Manuka Hill Farmlet offers the space to live more deliberately without sacrificing comfort or design. The home sits lightly within productive grounds, with wide views across paddocks and mature shelter belts from the main living areas. A central wood-burning stove, generous kitchen, and covered veranda create a welcoming heart, while the land includes established fruit trees, fenced grazing areas, and a substantial barn for storage or hobbies. The property is equally suited to an active family, a small-scale rural venture, or a restorative country base.',
    highlights:
      'Productive grounds, a substantial barn, and a well-finished home with wide rural views and excellent outdoor connection.',
    amenities: [
      'Fenced paddocks with water points',
      'Large machinery barn',
      'Wood-burning stove',
      'Orchard and kitchen garden',
      'Covered veranda with outdoor fireplace',
    ],
    neighborhood:
      'Cambridge offers excellent schools, cycling routes, equestrian facilities, and a thriving village centre within easy driving distance.',
    tenure: 'Freehold title',
    rates: 'Approx. NZ$5,180 per year',
    agent: 'Polaris Private Property Team',
    features: [
      '4.8 hectares of land',
      'Productive orchard',
      'Large barn and workshop',
      'Sheltered outdoor living',
      'Rural views in every direction',
    ],
    images: [
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600585152915-d208bec867a1?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1600&q=85',
    ],
  },
  {
    id: 'garden-street-cottage',
    name: 'Garden Street Cottage',
    type: 'Restored Character Home',
    location: 'Christchurch Central, Canterbury',
    price: 875000,
    status: 'For sale',
    bedrooms: 3,
    bathrooms: 2,
    area: '164 m²',
    lotSize: '492 m²',
    yearBuilt: 1912,
    parking: 'Off-street parking for two',
    summary:
      'A character cottage carefully renewed for modern life, with original details, a sunny garden, and a central address.',
    description:
      "Garden Street Cottage balances the romance of an early twentieth-century home with the convenience of a thoughtful renovation. Original timber floors, high ceilings, and restored sash windows sit comfortably alongside a modern kitchen, updated bathrooms, and discreetly integrated services. The rear living room opens to a sun-filled garden and covered deck, while three bedrooms provide a flexible layout for a couple, family, or work-from-home arrangement. Every update has been made with respect for the home's proportions and personality.",
    highlights:
      'Restored character details, a sheltered garden, and a central location close to parks, schools, and the arts precinct.',
    amenities: [
      'Restored timber flooring',
      'Updated kitchen and bathrooms',
      'Heat pump and insulation upgrade',
      'Covered rear deck',
      'Secure garden studio',
    ],
    neighborhood:
      "A walkable central-city location near Hagley Park, cafes, schools, galleries, and Christchurch's revitalised cultural precinct.",
    tenure: 'Freehold title',
    rates: 'Approx. NZ$3,780 per year',
    agent: 'Polaris Private Property Team',
    features: [
      'Original character details',
      'Three flexible bedrooms',
      'Separate garden studio',
      'Sunny private garden',
      'Walkable central location',
    ],
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600585152915-d208bec867a1?auto=format&fit=crop&w=1600&q=85',
    ],
  },
  {
    id: 'silver-oaks-estate',
    name: 'Silver Oaks Estate',
    type: 'Country Manor',
    location: 'Martinborough, Wairarapa',
    price: 1890000,
    status: 'New listing',
    bedrooms: 5,
    bathrooms: 3,
    area: '376 m²',
    lotSize: '3.1 ha',
    yearBuilt: 2008,
    parking: 'Triple garage and guest parking',
    summary:
      'A gracious country manor surrounded by old trees, vineyard country, and beautifully considered entertaining spaces.',
    description:
      'Silver Oaks Estate is a substantial country home with a sense of permanence and a generous relationship to its grounds. The formal entrance leads to a sequence of living rooms that open onto verandas and lawns, while the kitchen and family room form a more relaxed everyday centre. Five bedrooms include a spacious guest wing, and the grounds offer mature oaks, a small orchard, and room for horses or future garden projects. The home is made for long lunches, quiet mornings, and the particular pleasure of having space around you.',
    highlights:
      'Mature park-like grounds, a flexible guest wing, and elegant entertaining spaces in the heart of Wairarapa wine country.',
    amenities: [
      'Formal library and sitting room',
      'Wraparound covered veranda',
      'Guest wing with separate entry',
      'Stable or hobby shed',
      'Mature orchard and oak grove',
    ],
    neighborhood:
      'Martinborough is celebrated for its vineyards, food culture, village character, and easy access to the Wairarapa landscape and coast.',
    tenure: 'Freehold title',
    rates: 'Approx. NZ$6,420 per year',
    agent: 'Polaris Private Property Team',
    features: [
      'Park-like mature grounds',
      'Five generous bedrooms',
      'Separate guest wing',
      'Triple garaging',
      'Orchard and hobby land',
    ],
    images: [
      'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=85',
    ],
  },
];

module.exports = houses;
