const houses = [
  {
    id: 'harbour-view-residence',
    name: 'Harbour View Residence',
    type: 'Contemporary Villa',
    location: 'Takapuna, Auckland',
    price: 1280000,
    status: 'For sale',
    bedrooms: 4,
    bathrooms: 3,
    area: '286 m²',
    lotSize: '612 m²',
    yearBuilt: 2021,
    parking: 'Double garage',
    summary:
      'A light-filled coastal villa with harbour outlooks, considered finishes, and generous spaces for entertaining.',
    description:
      'Harbour View Residence is a carefully composed coastal home designed around light, privacy, and effortless connection to the water. The main living level opens through wide glass sliders to a landscaped courtyard and elevated terrace, creating a natural flow between the kitchen, dining room, and outdoor entertaining area. Inside, warm oak flooring balances crisp architectural lines, while the stone kitchen, tailored joinery, and quiet study provide the polish expected of a contemporary villa. The upper-level suite captures the best of the harbour outlook and gives the home a peaceful retreat from its social spaces.',
    highlights:
      'Morning harbour views, a north-facing terrace, and a flexible media room make this a polished home for both everyday life and relaxed entertaining.',
    amenities: [
      'Designer kitchen with integrated appliances',
      'Ducted heat pump system',
      'Underfloor heating in bathrooms',
      'Secure video entry',
      'Rainwater collection for garden irrigation',
    ],
    neighborhood:
      'Set close to Takapuna Beach, local cafes, schools, and the North Shore transport network, the residence offers an easy coastal lifestyle without giving up city access.',
    tenure: 'Freehold title',
    rates: 'Approx. NZ$5,840 per year',
    agent: 'Polaris Private Property Team',
    features: [
      'Open-plan kitchen with stone island',
      'Floor-to-ceiling double glazing',
      'Private landscaped courtyard',
      'Home office and media room',
      'Solar-ready roof and smart lighting',
    ],
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=85',
    ],
  },
  {
    id: 'cedar-grove-house',
    name: 'Cedar Grove House',
    type: 'Family Home',
    location: 'Remuera, Auckland',
    price: 985000,
    status: 'For sale',
    bedrooms: 3,
    bathrooms: 2,
    area: '198 m²',
    lotSize: '438 m²',
    yearBuilt: 2018,
    parking: 'Covered carport',
    summary:
      'A warm, established family home with mature gardens, a sunny deck, and an easy indoor-outdoor layout.',
    description:
      'Cedar Grove House brings together the reassuring proportions of a family home and the relaxed feel of a garden retreat. The central living room is anchored by a feature timber wall and opens directly onto a west-facing deck for late afternoon gatherings. Three generous bedrooms include a private main suite, while a separate laundry, flexible study nook, and generous storage make the home practical as well as welcoming. Established planting frames the property from the street and creates a private green outlook from nearly every room.',
    highlights:
      'A beautifully maintained garden, broad entertaining deck, and practical single-level layout make this an inviting long-term family address.',
    amenities: [
      'Engineered oak flooring',
      'Gas fireplace and heat pump',
      'Double-glazed timber windows',
      'Raised vegetable beds',
      'Fibre internet connection',
    ],
    neighborhood:
      'Remuera village, sought-after schools, parks, and daily conveniences are all within easy reach, with the city centre a short drive away.',
    tenure: 'Freehold title',
    rates: 'Approx. NZ$4,920 per year',
    agent: 'Polaris Private Property Team',
    features: [
      'West-facing entertaining deck',
      'Engineered oak flooring',
      'Separate laundry room',
      'Mature native garden',
      'Walkable to local schools and cafes',
    ],
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600585152915-d208bec867a1?auto=format&fit=crop&w=1600&q=85',
    ],
  },
  {
    id: 'olive-ridge-retreat',
    name: 'Olive Ridge Retreat',
    type: 'Country Estate',
    location: 'Matakana, Auckland',
    price: 1765000,
    status: 'New listing',
    bedrooms: 5,
    bathrooms: 3,
    area: '342 m²',
    lotSize: '2.4 ha',
    yearBuilt: 2020,
    parking: 'Triple garage',
    summary:
      'A private country estate with a pool terrace, guest suite, orchard, and expansive rural views.',
    description:
      'Olive Ridge Retreat is a rare country holding that combines architectural clarity with the generosity of a rural setting. The five-bedroom main residence is arranged around a sunlit central living zone, with high ceilings, natural stone, and full-height glazing framing the changing landscape. A separate guest suite provides privacy for extended family or visitors, while the pool terrace, outdoor kitchen, orchard, and established olive grove turn the grounds into a destination of their own. Despite its sense of escape, the property remains close to Matakana markets, vineyards, beaches, and village amenities.',
    highlights:
      'A private pool, established olive grove, and versatile guest accommodation give this estate both lifestyle appeal and long-term flexibility.',
    amenities: [
      'Heated mineral swimming pool',
      'Outdoor kitchen and firepit',
      'Rainwater storage tanks',
      'Three-phase power to workshop',
      'Underfloor heating throughout living areas',
    ],
    neighborhood:
      'Matakana is known for its weekend markets, artisan producers, beaches, and relaxed village atmosphere, with Auckland accessible for city connections.',
    tenure: 'Freehold title',
    rates: 'Approx. NZ$6,780 per year',
    agent: 'Polaris Private Property Team',
    features: [
      'Heated mineral swimming pool',
      'Wraparound rural views',
      'Guest suite with private entry',
      'Orchard and established olive grove',
      'Workshop and triple garaging',
    ],
    images: [
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1600&q=85',
    ],
  },
  {
    id: 'laneway-loft-residence',
    name: 'Laneway Loft Residence',
    type: 'Industrial Loft',
    location: 'Te Aro, Wellington',
    price: 1095000,
    status: 'For sale',
    bedrooms: 2,
    bathrooms: 2,
    area: '142 m²',
    lotSize: 'Private roof terrace',
    yearBuilt: 2019,
    parking: 'Secure basement parking',
    summary:
      'A characterful city loft with soaring ceilings, original industrial details, and a private roof terrace above Te Aro.',
    description:
      'Laneway Loft Residence occupies the upper levels of a carefully converted warehouse in the centre of Wellington. Original timber beams, exposed brick, and tall steel-framed windows give the home a strong architectural identity, while a modern kitchen and two well-separated bedrooms make it comfortable for everyday living. The open living level rises above the laneway and opens to a private roof terrace with city views, creating a rare outdoor room in the heart of Te Aro.',
    highlights:
      'Original warehouse character, a private rooftop terrace, and a walkable central-city setting surrounded by Wellington dining and culture.',
    amenities: [
      'Exposed brick and timber beams',
      'Bespoke kitchen with brass fixtures',
      'Private roof terrace with city views',
      'Secure lift and basement parking',
      'Acoustic glazing to laneway frontage',
    ],
    neighborhood:
      "Te Aro places theatres, galleries, restaurants, the waterfront, and Wellington's creative community within an easy walk.",
    tenure: 'Unit title with body corporate',
    rates: 'Approx. NZ$4,240 per year',
    agent: 'Polaris Private Property Team',
    features: [
      'Original warehouse structure',
      'Private rooftop entertaining',
      'Two generous bedroom suites',
      'Walkable central location',
      'Secure basement car park',
    ],
    images: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600585154367-2e1296b8f0a4?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=85',
    ],
  },
  {
    id: 'pohutukawa-coast-house',
    name: 'Pohutukawa Coast House',
    type: 'Beachside Bungalow',
    location: 'Mount Maunganui, Bay of Plenty',
    price: 1495000,
    status: 'New listing',
    bedrooms: 4,
    bathrooms: 2,
    area: '224 m²',
    lotSize: '506 m²',
    yearBuilt: 2019,
    parking: 'Double garage',
    summary:
      'A relaxed beachside home with generous decks, coastal planting, and room for weekends that stretch into summer.',
    description:
      'Pohutukawa Coast House captures the easy rhythm of life by the sea. The open-plan living area is oriented to the north and opens onto wide timber decks, allowing the home to move naturally between indoor comfort and outdoor entertaining. Four bedrooms provide a flexible arrangement for family and guests, with the ground-floor suite ideal for visitors or independent teenagers. Durable finishes, abundant storage, and an outdoor shower make the property as practical as it is inviting after a morning at the beach.',
    highlights:
      'A short walk to the sand, generous entertaining decks, and a private outdoor shower make this a true coastal lifestyle home.',
    amenities: [
      'Outdoor shower and surf storage',
      'North-facing covered deck',
      'Heat pump in living area',
      'Built-in outdoor barbecue',
      'Low-maintenance coastal garden',
    ],
    neighborhood:
      'Enjoy the cafes, surf culture, walking trails, and broad beaches of Mount Maunganui with local schools and shops close by.',
    tenure: 'Freehold title',
    rates: 'Approx. NZ$5,360 per year',
    agent: 'Polaris Private Property Team',
    features: [
      'Four flexible bedrooms',
      'Covered outdoor entertaining',
      'Beach gear storage',
      'Private garden',
      'Walkable beach location',
    ],
    images: [
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1544984243-ec57ea16fe25?auto=format&fit=crop&w=1600&q=85',
    ],
  },
  {
    id: 'fern-bank-residence',
    name: 'Fern Bank Residence',
    type: 'Modern Family Home',
    location: "Havelock North, Hawke's Bay",
    price: 1240000,
    status: 'For sale',
    bedrooms: 4,
    bathrooms: 2,
    area: '248 m²',
    lotSize: '1,120 m²',
    yearBuilt: 2017,
    parking: 'Double garage plus studio bay',
    summary:
      'A generous garden property with a smart floor plan, sheltered entertaining, and room to grow.',
    description:
      'Fern Bank Residence offers the space and composure of a country town home with a level of finish that makes everyday living feel special. The living wing is arranged to catch afternoon sun and opens to a sheltered terrace overlooking lawns and mature planting. A separate studio bay provides an excellent creative workspace or home gym, while the four-bedroom plan gives growing households room to adapt. The property has been cared for with an emphasis on durability, warmth, and easy connection to the garden.',
    highlights:
      'A large, private section with a flexible studio bay and a sun-soaked terrace for family gatherings.',
    amenities: [
      'Wood-burning fireplace',
      'Covered alfresco terrace',
      'Garden irrigation system',
      'Separate studio or gym',
      'Fruit trees and raised beds',
    ],
    neighborhood:
      "Havelock North offers village cafes, excellent local produce, wineries, parks, and a strong community setting within Hawke's Bay.",
    tenure: 'Freehold title',
    rates: 'Approx. NZ$4,460 per year',
    agent: 'Polaris Private Property Team',
    features: [
      'Large landscaped section',
      'Separate studio bay',
      'Sheltered outdoor room',
      'Four double bedrooms',
      'Excellent storage',
    ],
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1600&q=85',
    ],
  },
  {
    id: 'summit-lane-penthouse',
    name: 'Summit Lane Penthouse',
    type: 'City Penthouse',
    location: 'Auckland Central, Auckland',
    price: 2190000,
    status: 'For sale',
    bedrooms: 3,
    bathrooms: 3,
    area: '231 m²',
    lotSize: 'Private rooftop terrace',
    yearBuilt: 2023,
    parking: 'Secure tandem parking',
    summary:
      'A private city residence with dramatic views, generous entertaining rooms, and a rooftop terrace above it all.',
    description:
      'Summit Lane Penthouse occupies the top level of a discreet boutique building and delivers a rare combination of privacy, scale, and central convenience. The main living space frames layered harbour and skyline views through full-height glazing, while a sculptural kitchen and dining area provide an elegant setting for entertaining. The private rooftop terrace is equipped for long summer evenings, and three ensuite-capable bedrooms allow the home to operate equally well as a primary residence, city base, or executive retreat.',
    highlights:
      'Panoramic city and harbour outlooks, a private rooftop terrace, and boutique-building privacy in the heart of Auckland.',
    amenities: [
      'Private lift access',
      'Smart climate and lighting controls',
      'Rooftop outdoor kitchen',
      'Secure parcel room',
      'Two side-by-side storage lockers',
    ],
    neighborhood:
      'Restaurants, galleries, the waterfront, and major business precincts are all within an easy walk, making this a highly connected city address.',
    tenure: 'Unit title with body corporate',
    rates: 'Approx. NZ$7,250 per year',
    agent: 'Polaris Private Property Team',
    features: [
      'Private lift lobby',
      'Panoramic harbour views',
      'Three generous suites',
      'Rooftop entertaining terrace',
      'Two secure car parks',
    ],
    images: [
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=1600&q=85',
    ],
  },
  {
    id: 'the-terrace-at-lake-hayes',
    name: 'The Terrace at Lake Hayes',
    type: 'Alpine Retreat',
    location: 'Arrowtown, Queenstown',
    price: 2450000,
    status: 'Private release',
    bedrooms: 4,
    bathrooms: 3,
    area: '310 m²',
    lotSize: '1,860 m²',
    yearBuilt: 2020,
    parking: 'Double garage with gear room',
    summary:
      'A warm architectural retreat framed by mountain light, lake air, and generous spaces for gathering.',
    description:
      'The Terrace at Lake Hayes is an alpine home with a strong sense of arrival and a deeply comfortable interior life. Natural stone, oak, and wool textures soften the clean architectural envelope, while expansive windows draw the surrounding peaks into the living spaces. The plan includes a generous bunk or guest room, a dedicated gear room, and a sheltered terrace positioned for afternoon sun. It is a retreat designed for both quiet weekends and memorable gatherings in every season.',
    highlights:
      'Mountain views, a sheltered terrace, and thoughtful ski and outdoor gear facilities create a true four-season retreat.',
    amenities: [
      'Hydronic underfloor heating',
      'Stone hearth fireplace',
      'Heated gear room',
      'Outdoor cedar hot tub',
      'Integrated sound system',
    ],
    neighborhood:
      'A short drive from Arrowtown village, Lake Hayes, and Queenstown recreation, with direct access to trails, vineyards, and ski fields.',
    tenure: 'Freehold title',
    rates: 'Approx. NZ$8,120 per year',
    agent: 'Polaris Private Property Team',
    features: [
      'Mountain and lake outlooks',
      'Outdoor cedar hot tub',
      'Dedicated gear room',
      'Four-season entertaining terrace',
      'Guest accommodation',
    ],
    images: [
      'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=85',
    ],
  },
  {
    id: 'mariner-house',
    name: 'Mariner House',
    type: 'Waterfront Residence',
    location: 'Devonport, Auckland',
    price: 1980000,
    status: 'For sale',
    bedrooms: 4,
    bathrooms: 3,
    area: '267 m²',
    lotSize: '584 m²',
    yearBuilt: 2016,
    parking: 'Double garage',
    summary:
      'A gracious waterfront home with a private jetty outlook, generous living rooms, and an elegant garden setting.',
    description:
      'Mariner House is a generous waterfront residence with a quiet, collected character. The home has been planned for the way people actually live, with a formal sitting room for winter evenings, an open kitchen and family room for daily life, and a broad terrace that looks towards the water. The upper-level main suite includes a private balcony, while the lower guest room and full bathroom provide flexibility for visitors or multigenerational living. Mature gardens soften the boundaries and create a rare sense of privacy by the shore.',
    highlights:
      'Water views from multiple rooms, mature gardens, and a flexible layout suited to both family life and hosting.',
    amenities: [
      'Water-facing entertaining terrace',
      'Private mooring access nearby',
      'Gas fireplace',
      'Security alarm system',
      'Landscaped garden with irrigation',
    ],
    neighborhood:
      'Devonport village, ferry connections, beaches, and local dining are close by, with the Auckland CBD accessible across the harbour.',
    tenure: 'Freehold title',
    rates: 'Approx. NZ$6,940 per year',
    agent: 'Polaris Private Property Team',
    features: [
      'Water views from main rooms',
      'Private upper balcony',
      'Flexible guest accommodation',
      'Mature landscaped garden',
      'Close to ferry and village',
    ],
    images: [
      'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1544984243-ec57ea16fe25?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=1600&q=85',
    ],
  },
  //   {
  //     id: 'kauri-coast-retreat',
  //     name: 'Kauri Coast Retreat',
  //     type: 'Bushside Coastal Home',
  //     location: 'Whangarei Heads, Northland',
  //     price: 1375000,
  //     status: 'For sale',
  //     bedrooms: 3,
  //     bathrooms: 2,
  //     area: '214 m²',
  //     lotSize: '3,840 m²',
  //     yearBuilt: 2016,
  //     parking: 'Double carport plus boat pad',
  //     summary:
  //       'A secluded coastal retreat tucked between native bush and the harbour, with a boat pad, outdoor bath, and wide water views.',
  //     description:
  //       'Kauri Coast Retreat is a private coastal home designed for slower weekends and long summer days. The cedar-clad residence sits within a sheltered clearing, with native bush rising behind it and the harbour opening out beyond the front lawn. A generous kitchen and living room connect to a deep covered deck, while the main suite looks toward the water and a separate bunk room gives guests their own space. An outdoor bath, boat pad, kayak storage, and a network of walking tracks make the setting as useful as it is beautiful.',
  //     highlights:
  //       'Private harbour outlooks, native bush, and direct access to a quiet coastal setting with room for boats, kayaks, and long outdoor meals.',
  //     amenities: [
  //       'Cedar-clad exterior and wood burner',
  //       'Deep covered deck with outdoor kitchen',
  //       'Private outdoor soaking bath',
  //       'Boat pad and enclosed kayak store',
  //       'Native bush walking trails',
  //     ],
  //     neighborhood:
  //       'Whangarei Heads offers secluded beaches, harbour boating, native forest walks, and a close-knit coastal community within reach of Whangarei.',
  //     tenure: 'Freehold title',
  //     rates: 'Approx. NZ$4,180 per year',
  //     agent: 'Polaris Private Property Team',
  //     features: [
  //       'Harbour and bush outlooks',
  //       'Private outdoor bath',
  //       'Boat and kayak storage',
  //       'Three flexible bedrooms',
  //       'Sheltered coastal garden',
  //     ],
  //     images: [
  //       'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=85',
  //       'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1600&q=85',
  //       'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1600&q=85',
  //       'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=85',
  //     ],
  //   },
  //   {
  //     id: 'garden-street-cottage',
  //     name: 'Garden Street Cottage',
  //     type: 'Restored Character Home',
  //     location: 'Christchurch Central, Canterbury',
  //     price: 875000,
  //     status: 'For sale',
  //     bedrooms: 3,
  //     bathrooms: 2,
  //     area: '164 m²',
  //     lotSize: '492 m²',
  //     yearBuilt: 1912,
  //     parking: 'Off-street parking for two',
  //     summary:
  //       'A character cottage carefully renewed for modern life, with original details, a sunny garden, and a central address.',
  //     description:
  //       "Garden Street Cottage balances the romance of an early twentieth-century home with the convenience of a thoughtful renovation. Original timber floors, high ceilings, and restored sash windows sit comfortably alongside a modern kitchen, updated bathrooms, and discreetly integrated services. The rear living room opens to a sun-filled garden and covered deck, while three bedrooms provide a flexible layout for a couple, family, or work-from-home arrangement. Every update has been made with respect for the home's proportions and personality.",
  //     highlights:
  //       'Restored character details, a sheltered garden, and a central location close to parks, schools, and the arts precinct.',
  //     amenities: [
  //       'Restored timber flooring',
  //       'Updated kitchen and bathrooms',
  //       'Heat pump and insulation upgrade',
  //       'Covered rear deck',
  //       'Secure garden studio',
  //     ],
  //     neighborhood:
  //       "A walkable central-city location near Hagley Park, cafes, schools, galleries, and Christchurch's revitalised cultural precinct.",
  //     tenure: 'Freehold title',
  //     rates: 'Approx. NZ$3,780 per year',
  //     agent: 'Polaris Private Property Team',
  //     features: [
  //       'Original character details',
  //       'Three flexible bedrooms',
  //       'Separate garden studio',
  //       'Sunny private garden',
  //       'Walkable central location',
  //     ],
  //     images: [
  //       'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=1600&q=85',
  //       'https://images.unsplash.com/photo-1544984243-ec57ea16fe25?auto=format&fit=crop&w=1600&q=85',
  //       'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=85',
  //       'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1600&q=85',
  //     ],
  //   },
  //   {
  //     id: 'silver-oaks-estate',
  //     name: 'Silver Oaks Estate',
  //     type: 'Country Manor',
  //     location: 'Martinborough, Wairarapa',
  //     price: 1890000,
  //     status: 'New listing',
  //     bedrooms: 5,
  //     bathrooms: 3,
  //     area: '376 m²',
  //     lotSize: '3.1 ha',
  //     yearBuilt: 2008,
  //     parking: 'Triple garage and guest parking',
  //     summary:
  //       'A gracious country manor surrounded by old trees, vineyard country, and beautifully considered entertaining spaces.',
  //     description:
  //       'Silver Oaks Estate is a substantial country home with a sense of permanence and a generous relationship to its grounds. The formal entrance leads to a sequence of living rooms that open onto verandas and lawns, while the kitchen and family room form a more relaxed everyday centre. Five bedrooms include a spacious guest wing, and the grounds offer mature oaks, a small orchard, and room for horses or future garden projects. The home is made for long lunches, quiet mornings, and the particular pleasure of having space around you.',
  //     highlights:
  //       'Mature park-like grounds, a flexible guest wing, and elegant entertaining spaces in the heart of Wairarapa wine country.',
  //     amenities: [
  //       'Formal library and sitting room',
  //       'Wraparound covered veranda',
  //       'Guest wing with separate entry',
  //       'Stable or hobby shed',
  //       'Mature orchard and oak grove',
  //     ],
  //     neighborhood:
  //       'Martinborough is celebrated for its vineyards, food culture, village character, and easy access to the Wairarapa landscape and coast.',
  //     tenure: 'Freehold title',
  //     rates: 'Approx. NZ$6,420 per year',
  //     agent: 'Polaris Private Property Team',
  //     features: [
  //       'Park-like mature grounds',
  //       'Five generous bedrooms',
  //       'Separate guest wing',
  //       'Triple garaging',
  //       'Orchard and hobby land',
  //     ],
  //     images: [
  //       'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=85',
  //       'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=85',
  //       'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85',
  //       'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1600&q=85',
  //     ],
  //   },
];

const propertyGalleries = {
  'harbour-view-residence': [
    'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/210617/pexels-photo-210617.jpeg?auto=compress&cs=tinysrgb&w=1600',
  ],
  'cedar-grove-house': [
    'https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/534151/pexels-photo-534151.jpeg?auto=compress&cs=tinysrgb&w=1600',
  ],
  'olive-ridge-retreat': [
    'https://images.pexels.com/photos/703160/pexels-photo-703160.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/280223/pexels-photo-280223.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/1115804/pexels-photo-1115804.jpeg?auto=compress&cs=tinysrgb&w=1600',
  ],
  'laneway-loft-residence': [
    'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/157811/pexels-photo-157811.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1600',
  ],
  'pohutukawa-coast-house': [
    'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg?auto=compress&cs=tinysrgb&w=1600',
  ],
  'fern-bank-residence': [
    'https://images.pexels.com/photos/280228/pexels-photo-280228.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/209296/pexels-photo-209296.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/280229/pexels-photo-280229.jpeg?auto=compress&cs=tinysrgb&w=1600',
  ],
  'summit-lane-penthouse': [
    'https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/276722/pexels-photo-276722.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/260689/pexels-photo-260689.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/280230/pexels-photo-280230.jpeg?auto=compress&cs=tinysrgb&w=1600',
  ],
  'the-terrace-at-lake-hayes': [
    'https://images.pexels.com/photos/1642125/pexels-photo-1642125.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/280225/pexels-photo-280225.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/280224/pexels-photo-280224.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/210538/pexels-photo-210538.jpeg?auto=compress&cs=tinysrgb&w=1600',
  ],
  'mariner-house': [
    'https://images.pexels.com/photos/1022936/pexels-photo-1022936.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/280221/pexels-photo-280221.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/280226/pexels-photo-280226.jpeg?auto=compress&cs=tinysrgb&w=1600',
  ],
};

houses.forEach((house) => {
  house.images = propertyGalleries[house.id] || house.images;
});

module.exports = houses;
